export type IIcons = {
  [K in IIconType]: string;
};

export type IIconType =
  | 'arrow-up'
  | 'arrow-down'
  | 'burger-open'
  | 'burger-close'
  | 'play'
  | 'crm'
  | 'calendar'
  | 'document'
  | 'mail'
  | 'timeout-playIcon'
  | 'start-line'
  | 'active-bg'
  | 'eur'
  | 'usd'
  | 'crm-dark'
  | 'calendar-dark'
  | 'document-dark'
  | 'mail-dark'
  | 'search'
  | 'plus-icon'
  | 'comment'
  | 'plus-gray'
  | 'userIcon'
  | 'delete'
  | 'edit'
  | 'link'
  | 'history-edit'
  | 'history-todo'
  | 'history-accounts'
  | 'history-comment'
  | 'history-deal-create'
  | 'arrow-left'
  | 'clip'
  | 'calendar-outline'
  | 'count-plus-active'
  | 'count-minus-active'
  | 'count-minus-unactive'
  | 'birthday'
  | 'note'
  | 'download'
  | 'break';
